version: "3.8"

services:
  redis:
    image: redis:8.0-alpine
    container_name: limiter-redis
    ports:
      - "6379:6379"

  rest:
    build: .
    container_name: limiter-http
    depends_on:
      - redis
    environment:
      - SERVER_PORT=8080
      - REDIS_ADDR=redis:6379
    ports:
      - "8080:8080"